services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama-network

  ollama-api:
    build: .
    container_name: ollama-api
    ports:
      - "80:3000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PORT=3000
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama_data:
